language: php

php:
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/phplint
  - ./vendor/bin/phpcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

matrix:
  fast_finish: true
